Agent:
  num_steps: 3000000
  batch_size: 64
  memory_size: 100000
  update_interval: 1
  start_steps: 0
  log_interval: 10
  # no evaluation
  eval_interval: 5000000
  num_eval_episodes: 5

SAC:
  gamma: 0.99
  nstep: 1
  policy_lr: 0.0003
  q_lr: 0.0003
  entropy_lr: 0.0003
  policy_hidden_units: [64, 64]
  q_hidden_units: [64, 64]
  target_update_coef: 0.005
  log_interval: 1

DisCor:
  error_lr: 0.0003
  error_hidden_units: [256, 256, 256]
  tau_init: 10.0
